import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import { navLinks } from '@/constants';
import { CiLogout } from 'react-icons/ci';
import Image from 'next/image';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Althera',
    description: 'Generated by create next app',
    
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <div className="flex">
                    {/* Sidebar */}
                    <div className="fixed left-0 top-0 h-full w-32 bg-primary-dark-blue shadow-lg">
                        {/* LOGO ALTHERA */}
                        <div className="px-5 py-2">
                            <Image src="/logos/logo_althera_blanc.png" alt="Logo" width={120} height={120} priority />
                        </div>
                        {/* Menu Items */}
                        <div className="flex w-full flex-col items-center">
                            {navLinks.map((link) => {
                                return (
                                    <Link
                                        key={link.label}
                                        href={link.href}
                                        className="text-md w-full py-1 pl-2 font-semibold text-white transition-all duration-200 hover:text-secondary-light-blue"
                                    >
                                        {link.label}
                                    </Link>
                                );
                            })}
                        </div>
                        {/* Logout */}
                        <div className="absolute bottom-0 flex w-full flex-col items-center">
                            <CiLogout className="block h-8 w-full cursor-pointer py-1 text-light-white hover:text-secondary-light-blue" />
                        </div>
                    </div>
                    <div className="ml-32 flex-1">{children}</div>
                </div>
            </body>
        </html>
    );
}

