// <auto-generated />
using System;
using Althera.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Althera.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicDB", b =>
                {
                    b.Property<int>("clinicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("clinicId"));

                    b.Property<string>("clinicAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clinicName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clinicPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("clinicId");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("OrderDB", b =>
                {
                    b.Property<int>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderId"));

                    b.Property<DateTime?>("orderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("orderState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("orthesisComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("orthesisInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("orthesisModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("orthesisScan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("patientId")
                        .HasColumnType("int");

                    b.HasKey("orderId");

                    b.HasIndex("patientId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PatientDB", b =>
                {
                    b.Property<int>("patientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("patientId"));

                    b.Property<int>("clinicId")
                        .HasColumnType("int");

                    b.Property<int?>("healthInsuranceCard")
                        .HasColumnType("int");

                    b.Property<string>("patientFirstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientLastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("patientId");

                    b.HasIndex("clinicId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("OrderDB", b =>
                {
                    b.HasOne("PatientDB", "Patient")
                        .WithMany("Orders")
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientDB", b =>
                {
                    b.HasOne("ClinicDB", "Clinic")
                        .WithMany("Patients")
                        .HasForeignKey("clinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("ClinicDB", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("PatientDB", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
