using Althera.Api.Requests;
using Althera.Domain;
using Althera.Extensions;
using Althera.Models.Persistence;
using Althera.Persistence;

namespace Althera.Services;

public class ClinicsService(AppDbContext dbContext)
{
    private readonly AppDbContext _dbContext = dbContext;

    public List<Clinic> GetAll()
    {
        var clinicEntities = _dbContext.Clinics.ToList();
        return clinicEntities.Select(clinic => clinic.ToDomain()).ToList();
    }

    public Clinic? GetClinic(string id)
    {
        var clinicEntity = _dbContext.Clinics.SingleOrDefault(c => c.Id == id);
        return clinicEntity?.ToDomain();
    }

    public Clinic CreateClinic(ClinicCreateRequest clinicCreateRequest)
    {
        var clinicEntity = new ClinicEntity
        {
            Id = Guid.NewGuid().ToString(), // Check for AutoGenerated id from database
            Name = clinicCreateRequest.Name,
            Street = clinicCreateRequest.Street,
            City = clinicCreateRequest.City,
            Zip = clinicCreateRequest.Zip,
        };
        _dbContext.Clinics.Add(clinicEntity);
        _dbContext.SaveChanges();

        return clinicEntity.ToDomain();
    }

    public Clinic UpdateClinic(string id, ClinicUpdateRequest clinicUpdateRequest)
    {
        var clinicEntity = _dbContext.Clinics.SingleOrDefault(c => c.Id == id) ?? throw new InvalidOperationException("Clinic not found.");

        if (!string.IsNullOrEmpty(clinicUpdateRequest.Name))
        {
            clinicEntity.Name = clinicUpdateRequest.Name;
            _dbContext.SaveChanges();
        }

        return clinicEntity.ToDomain();
    }

    public void DeleteClinic(string id)
    {
        // TODO : We might want to 'soft delete' clinics (or deactivate), since some orders might be related to it.
        var clinic = _dbContext.Clinics.SingleOrDefault(c => c.Id == id) ?? throw new InvalidOperationException("Clinic not found.");
        _dbContext.Clinics.Remove(clinic);
        _dbContext.SaveChanges();
    }
}
