using Althera.Domain;
using Althera.Extensions;
using Althera.Models.Persistence;
using Althera.Persistence;
using Althera.Providers;
using Althera.Requests;

namespace Althera.Services;

public class PatientsService(ClinicProvider clinicProvider, AppDbContext dbContext)
{
    private readonly ClinicProvider _clinicProvider = clinicProvider;
    private readonly AppDbContext _dbContext = dbContext;

    public List<Patient> GetAll()
    {
        var patientEntities = _dbContext.Patients.ToList();
        return patientEntities.Select(patient => patient.ToDomain()).ToList();
    }

    public Patient? GetPatient(string id)
    {
        var patientEntity = _dbContext.Patients.SingleOrDefault(x => x.Id == id);
        return patientEntity?.ToDomain();
    }

    public Patient CreatePatient(PatientCreateRequest patientCreateRequest)
    {
        var patientEntity = new PatientEntity
        {
            Id = Guid.NewGuid().ToString(), // Check for AutoGenerated id from database
            FirstName = patientCreateRequest.FirstName,
            LastName = patientCreateRequest.LastName,
            HealthInsuranceNumber = patientCreateRequest.HealthInsuranceNumber,
            ClinicId = _clinicProvider.ClinicId
        };
        _dbContext.Patients.Add(patientEntity);
        _dbContext.SaveChanges();

        return patientEntity.ToDomain();
    }

    public Patient UpdatePatient(string id, PatientUpdateRequest patientUpdateRequest)
    {
        var patientEntity = _dbContext.Patients.SingleOrDefault(p => p.Id == id) ?? throw new InvalidOperationException("Patient not found.");

        patientEntity.FirstName = string.IsNullOrEmpty(patientUpdateRequest.FirstName) ? patientEntity.FirstName : patientUpdateRequest.FirstName;
        patientEntity.LastName = string.IsNullOrEmpty(patientUpdateRequest.LastName) ? patientEntity.LastName : patientUpdateRequest.LastName;
        patientEntity.HealthInsuranceNumber = string.IsNullOrEmpty(patientUpdateRequest.HealthInsuranceNumber) ? patientEntity.HealthInsuranceNumber : patientUpdateRequest.HealthInsuranceNumber;
        _dbContext.SaveChanges();

        return patientEntity.ToDomain();

    }

    public void DeletePatient(string id)
    {
        // TODO : We might want to 'soft delete' patients, since some orders might be related to it.
        var patient = _dbContext.Patients.SingleOrDefault(p => p.Id == id) ?? throw new InvalidOperationException("Patient not found.");
        _dbContext.Patients.Remove(patient);
        _dbContext.SaveChanges();
    }
}