// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFGetStarted.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240719180204_AddCommande")]
    partial class AddCommande
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clinique", b =>
                {
                    b.Property<int>("cliniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cliniqueId"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomClinique")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cliniqueId");

                    b.ToTable("Cliniques");
                });

            modelBuilder.Entity("Commande", b =>
                {
                    b.Property<int>("commandeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("commandeId"));

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("commentaireOrthese")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("etatCommande")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("infoOrthese")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelorthese")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("scan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("commandeId");

                    b.HasIndex("PatientId");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("Patient", b =>
                {
                    b.Property<int>("patientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("patientId"));

                    b.Property<int>("CliniqueId")
                        .HasColumnType("int");

                    b.Property<string>("nomPatient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("numeroAssuranceMaladie")
                        .HasColumnType("int");

                    b.Property<string>("prenomPatient")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("patientId");

                    b.HasIndex("CliniqueId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Commande", b =>
                {
                    b.HasOne("Patient", "Patient")
                        .WithMany("Commandes")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Patient", b =>
                {
                    b.HasOne("Clinique", "Clinique")
                        .WithMany("Patients")
                        .HasForeignKey("CliniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinique");
                });

            modelBuilder.Entity("Clinique", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("Patient", b =>
                {
                    b.Navigation("Commandes");
                });
#pragma warning restore 612, 618
        }
    }
}
