@Althera_HostAddress = http://localhost:5125

GET {{Althera_HostAddress}}/patient/
Accept: application/json

###

POST {{Althera_HostAddress}}/patient/
Accept: application/json
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "healthInsuranceCard": "ABC12345",
  "clinicId": 1
}

###

PUT {{Althera_HostAddress}}/patient/3
Accept: application/json
Content-Type: application/json

{
  "id": 3,
  "firstName": "Jane",
  "lastName": "Doe",
  "healthInsuranceCard": "XYZ67890",
  "clinicId": 2
}

###

DELETE {{Althera_HostAddress}}/patient/3

###

GET {{Althera_HostAddress}}/commande/
Accept: application/json

###

POST {{Althera_HostAddress}}/commande/
Accept: application/json
Content-Type: application/json

{
  "IdPatient": 4,
  "dateCommande": "10/07/2024",
  "orthesisModel": "ModelX",
  "orthesisInfo": "Information",
  "orthesisScan": "ScanData",
  "orderState": "Pending",
  "orthesisComment": "No comments"
}

###

PUT {{Althera_HostAddress}}/commande/3
Accept: application/json
Content-Type: application/json

{
  "Id": 3,
  "IdPatient": 4,
  "dateCommande": "10/07/2024",
  "orthesisModel": "ModelY",
  "orthesisInfo": "Updated Information",
  "orthesisScan": "Updated ScanData",
  "orderState": "Completed",
  "orthesisComment": "Updated comment"
}

###

DELETE {{Althera_HostAddress}}/commande/3

###
    